name: Simple Workflow
on: [push]

jobs:
    main-check:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run a one-line script
              run: echo This job is running on ${{ runner.os }} and branch ${{ github.ref }} > output.txt
            - name: Archive the output
            uses: actions/upload-artifact@v2
            with:
                name: output
                path: output.txt
    read-output:
        needs: main-check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Download the artifact
              uses: actions/download-artifact@v2
              with:
                  name: output
            - name: Print the output
              run: cat output.txt